### ISSUE TITLE
get stuck when run with sudo

### ISSUE THREAD

**Issue by pendulm** [facebookincubator/below#8104]
It‘s Ok when run with unpriviledged user. But when run with sudo it get stuck, nothing responsive.
![image](https://user-images.githubusercontent.com/282373/130002171-e5d2cdb2-6d40-424e-b2a1-cf8c34cb9a06.png)

and CPU 100%
![image](https://user-images.githubusercontent.com/282373/130002172-e57b2200-b286-4d2a-bd9d-f1c08f4b877e.png)

**Comment by danobi** [comment]
Thanks for the report! I can reproduce this for below v0.2 but not below v0.3. Can you do `cargo install below` and see if the issue goes away?

BTW, I'll be out for the next couple days so I may respond later

**Comment by pendulm** [comment]
> Thanks for the report! I can reproduce this for below v0.2 but not below v0.3. Can you do `cargo install below` and see if the issue goes away?
> 
> BTW, I'll be out for the next couple days so I may respond later

YES. V0.3 works OK.
