### ISSUE TITLE
Invalid file format: "/proc/1/cgroup"

### ISSUE THREAD

**Issue by gdetrez** [facebookincubator/below#8105]
I installed below with dnf on Fedora 34, and I get this error when I try to start it:

```
❯❯❯ sudo below live
Aug 21 14:33:45.414 ERRO
----------------- Detected unclean exit ---------------------
Error Message: Invalid file format: "/proc/1/cgroup"
-------------------------------------------------------------
```
I also see the same error message over and over in journald.

In case it matters, before this I encountered the issue described in  #8103 (I had disabled cgroup v2 to install docker) but I fixed it (at least I think I did) and now I get the error above instead.

I'm not sure if I can provide good reproducible steps, as this is a fairly old Fedora install that has been updated and tweaked over the years.  But I'd appreciate any help diagnosing the issue further.

**Comment by brianc118** [comment]
@gdetrez could you show the output of `cat /proc/1/cgroup`? Sounds like cgroup2 isn't configured properly. We could probably improve the error message here.

**Comment by kanak** [comment]
I'm also on F34 and seeing the same error. Here's my /proc/1/cgroup:

```
cat /proc/1/cgroup
1:net_cls:/
0::/init.scope
```

**Comment by gdetrez** [comment]
@brianc118 I get the exact same output as @kanak.

**Comment by kakra** [comment]
Same problem on Gentoo, cgroupv2 is enabled:
```
# mount | grep cgroup2
cgroup2 on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate,memory_recursiveprot)

# cat /proc/1/cgroup
1:name=portage:/
0::/init.scope
```

It also shows `Invalid file format` for me.

**Comment by brianc118** [comment]
Feel free to test out the fix, otherwise you may have to wait a bit for a release.

**Comment by kakra** [comment]
@brianc118 Can confirm it works for Gentoo: Storing the patch in the package patches directory and re-installing v0.3 let's it start now at least. But I cannot verify if every other feature works as intended because it's the first time I'm running this anyways.
