### ISSUE TITLE
comparison request: Performance Co-Pilot

### ISSUE THREAD

**Issue by cuviper** [facebookincubator/below#8120]
Hi! Could you add a comparison to Performance Co-Pilot?
See https://pcp.io/ and https://github.com/performancecopilot/pcp

**Comment by cuviper** [comment]
cc @natoscott

**Comment by natoscott** [comment]
@cuviper me waves - heya Josh!

I wondered the same and chatted with the good folks working on this project a month or two back.  My thoughts after those discussions were it'd be a bit like comparing a formula one racing car to a space shuttle - we can compare them, but they're quite different beasts and its likely that the simple comparison points would do neither project justice.

We discussed the potential for below to use an optional, alternative back-end PMAPI implementation like htop nowadays provides via pcp-htop, such that a common on-disk and over-the-wire format could be shared between PCP and below - for folk who need the retrospective and/or distributed analysis functionality.  Would love to see that, just a Simple Matter Of Programming and of course finding time.

**Comment by cuviper** [comment]
Thanks, Nathan! I'll defer to you all whether you feel it's worthy of any comparison.

**Comment by dschatzberg** [comment]
At a high-level, below provides two core pieces of functionality:

1) A way to periodically record system performance metrics so they can be analyzed for post-hoc debugging (e.g. what happened at 2:30 AM yesterday?)
2) A terminal-based UI for displaying point-in-time system performance metrics.

You can thing of below as analogous to atop in the PCP ecosystem. My understanding is that in PCP you've modified atop to read data from PCP's data format - so only relying on atop's UI (e.g. using functionality #2, but not #1). As @natoscott mentions, one could imagine doing something similar with below. I'll go ahead and add this comparison
