### ISSUE TITLE
Version bump

### ISSUE THREAD

**Issue by hodgesds** [facebookincubator/below#8123]
Now that the [commit](https://github.com/facebookincubator/below/commit/038e9261ba6ddb1267a9cc99cb7d3126c6c72b54) has landed to fix the broken libbpf-rs dependency can we get a new release? The 0.4.0 version isn't so useful as it doesn't compile.

**Comment by brianc118** [comment]
Good point - let me do that now

**Comment by brianc118** [comment]
Closed with adbd1f489d4f47173b905b1602c698f458ec768f
