### ISSUE TITLE
Add option to show memory.{min,low,high,max) in Mem tab

### ISSUE THREAD

**Issue by jelmd** [facebookincubator/below#8170]
Would be helpful to show on demand the current values for `memory.{min,low,high,max)` right after the Slab columns in the **Mem** tab as well.

**Comment by brianc118** [comment]
I've thought of this before. I'm not sure if having it in the memory tab is a great idea, as it doesn't fit ni the category of "utilization" like the other stats. I wonder if it would make sense to have a separate tab for cgroup configuration (cpu, mem, io, etc.) and potentially add enabled controllers in the future as well.

**Comment by jelmd** [comment]
Switching between tabs which possibly have a different order/are not in sync? Hmm, IMHO not so good.

Actually I use it to get a feeling, how much mem different cgroups (actually containers) consume and whether we may need to adjust these values. Having to run a second instance (or switching to another tab) just to show the is inconvenient - not enough space on monitor| too old to remember all these values | to much time to resync the output in its head. So for an engineer's day-by-day work it is much better to have such columns right after or even before the 1st *Mem* col (Memory).

Isn't it possible to hide them per default and turn them on via hotkey?

**Comment by brianc118** [comment]
All valid points. I think some sort of hotkey that overlays limits next to the cgroup would be nice, but we'd have to be selective in what we show (one hotkey per property?).

I think for a first pass, I'll add a "Properties" tab, that shows things like enabled controllers, memory limits, cpu limits, cpuset, io weight etc. That should be pretty easy to do.

**Comment by jelmd** [comment]
Hmmm, ok let's see how it works. But as said, usually the memory limits are most important and seeing it right beside the current value would be very convenient. As a 1st try I would probably put it in a single column as min|low|high|max, etc. (because I guess, putting it in multiple columns is more work), i.e. the cpu weight|max|effective in CPU view, the memory min|low|high|max in Mem view, and the IO weight|max in the IO view. Side effect: in each view the same key binding (e.g. ctrl+l for limits) could be used?

**Comment by brianc118** [comment]
@jelmd 3c7f886df9d4e8e5951a2564d3305f5fc93dd04c adds a cgroup properties tab that displays memory.{low,high,max} etc.
