### ISSUE TITLE
CI broken due to `libbpf-rs` update

### ISSUE THREAD

**Issue by mmynk** [facebookincubator/below#8219]
The CI is broken due to the latest change for updating `libbpf-rs`: https://github.com/facebookincubator/below/commit/a6d5f017fc1c6b75b8820525a2a8b920cd6967c1.

Possibly because the line https://github.com/facebookincubator/below/blob/a6d5f017fc1c6b75b8820525a2a8b920cd6967c1/below/Cargo.toml#L59 still refers to `novendor` feature in `libbpf-rs` which was removed in rev https://github.com/libbpf/libbpf-rs/commit/291c6a4e0368c2f472078a8b8443fae427168179.

**Comment by d-e-s-o** [comment]
I am working on a fix.

**Comment by d-e-s-o** [comment]
Seems to be fixed now: https://github.com/facebookincubator/below/actions/runs/7757172994

**Comment by mmynk** [comment]
Awesome, thanks!
